name: Update Website Preview

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-preview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Capture screenshot
      run: |
        node -e "
        const puppeteer = require('puppeteer');
        (async () => {
          const browser = await puppeteer.launch();
          const page = await browser.newPage();
          await page.goto('https://weeknd-omega.vercel.app/');
          await page.screenshot({ path: 'website_preview.png', fullPage: true });
          await browser.close();
        })();
        "

    - name: Commit and push changes
      run: |
        git config --global TamalBht 'github-actions[bot]'
        git config --global bht.tamal@gmail.com 'github-actions[bot]@users.noreply.github.com'
        git add website_preview.png
        git commit -m 'Update website preview'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
